version: "2"

run:
  tests: false

linters:
  settings:
    dupl:
      threshold: 100

    gomoddirectives:
      replace-allow-list:
        - github.com/linode/linodego

    govet:
      disable:
        - shadow

    revive:
      rules:
        - name: unused-parameter
          severity: warning
          disabled: true

    staticcheck:
      checks: ["all", "-ST1005"]

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
