name: Docker Plugin Publish
on:
  workflow_dispatch: null
  release:
    types: [ published ]

permissions:
  contents: read
  id-token: write

jobs:
  oci_publish:
    name: Build and publish the docker plugin
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v7

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_ORGANIZATION }}
        env:
          DOCKERHUB_OIDC_CONNECTIONID: ${{ vars.DOCKERHUB_OIDC_CONNECTIONID }}

      - name: Build and push to DockerHub
        run: make deploy
        env:
          PLUGIN_VERSION: ${{ github.event.release.tag_name }}
